---

- name: debian | Apt-key add
  ansible.builtin.apt_key:
    keyring: "{{ item.keyring }}"
    url: "{{ item.url }}"
    id: "{{ item.id }}"
    state: "{{ item.state }}"
  loop: "{{ _apt_key[openjdk_release] }}"
  register: result
  until: result is succeeded

- name: debian | Apt-add-repository
  ansible.builtin.apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ _apt_repository[openjdk_release] }}"
  register: result
  until: result is succeeded

- name: debian | Apt-get install
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _apt[openjdk_release] }}"
  register: result
  until: result is succeeded
